### ISSUE TITLE
Segmentation fault in standalone mode

### ISSUE THREAD

**Issue by joao-intelliway** [ariga/atlas-provider-gorm#32]
I'm receiving a segmentation fault when I run the standalone program.

```Shell
$ go run -mod=mod ariga.io/atlas-provider-gorm load --path ./models --dialect sqlite
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5e6dfe]

goroutine 144 [running]:
go/types.(*Checker).handleBailout(0xc00032f200, 0xc000035bd0)
        /usr/local/go/src/go/types/check.go:367 +0x88
panic({0x708ee0?, 0x9a1080?})
        /usr/local/go/src/runtime/panic.go:770 +0x132
go/types.(*StdSizes).Sizeof(0x0, {0x7cb2a8, 0x9a4660})
        /usr/local/go/src/go/types/sizes.go:228 +0x31e
go/types.(*Config).sizeof(...)
        /usr/local/go/src/go/types/sizes.go:333
go/types.representableConst.func1({0x7cb2a8?, 0x9a4660?})
        /usr/local/go/src/go/types/const.go:76 +0x9e
go/types.representableConst({0x7cc5c8, 0x998640}, 0xc00032f200, 0x9a4660, 0x0)
        /usr/local/go/src/go/types/const.go:92 +0x192
go/types.(*Checker).arrayLength(0xc00032f200, {0x7cb838, 0xc00017d5e0?})
        /usr/local/go/src/go/types/typexpr.go:510 +0x2d3
go/types.(*Checker).typInternal(0xc00032f200, {0x7cb9e8, 0xc0007ac2d0}, 0x0)
        /usr/local/go/src/go/types/typexpr.go:299 +0x49d
go/types.(*Checker).definedType(0xc00032f200, {0x7cb9e8, 0xc0007ac2d0}, 0x7055e0?)
        /usr/local/go/src/go/types/typexpr.go:180 +0x37
go/types.(*Checker).varType(0xc00032f200, {0x7cb9e8, 0xc0007ac2d0})
        /usr/local/go/src/go/types/typexpr.go:145 +0x25
go/types.(*Checker).structType(0xc00032f200, 0xc0007ad890, 0xc0007ad890?)
        /usr/local/go/src/go/types/struct.go:113 +0x19f
go/types.(*Checker).typInternal(0xc00032f200, {0x7cb868, 0xc0000c7d70}, 0xc0007c0410)
        /usr/local/go/src/go/types/typexpr.go:316 +0x1345
go/types.(*Checker).definedType(0xc00032f200, {0x7cb868, 0xc0000c7d70}, 0x10?)
        /usr/local/go/src/go/types/typexpr.go:180 +0x37
go/types.(*Checker).typeDecl(0xc00032f200, 0xc0007c0410, 0xc00009f100, 0x0)
        /usr/local/go/src/go/types/decl.go:615 +0x44d
go/types.(*Checker).objDecl(0xc00032f200, {0x7cf7f8, 0xc0007c0410}, 0x0)
        /usr/local/go/src/go/types/decl.go:197 +0xa7f
go/types.(*Checker).packageObjects(0xc00032f200)
        /usr/local/go/src/go/types/resolver.go:681 +0x425
go/types.(*Checker).checkFiles(0xc00032f200, {0xc000030040, 0x2, 0x2})
        /usr/local/go/src/go/types/check.go:408 +0x1a5
go/types.(*Checker).Files(...)
        /usr/local/go/src/go/types/check.go:372
golang.org/x/tools/go/packages.(*loader).loadPackage(0xc0001a01c0, 0xc0000afa40)
        /home/user/go/pkg/mod/golang.org/x/tools@v0.10.0/go/packages/packages.go:1055 +0xa72
golang.org/x/tools/go/packages.(*loader).loadRecursive.func1()
        /home/user/go/pkg/mod/golang.org/x/tools@v0.10.0/go/packages/packages.go:854 +0x1a9
sync.(*Once).doSlow(0x6d6f616f6a2f656d?, 0x2f66726f6e65726f?)
        /usr/local/go/src/sync/once.go:74 +0xc2
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:65
golang.org/x/tools/go/packages.(*loader).loadRecursive(0x6e692f302e32332e?, 0x762f6c616e726574?)
        /home/user/go/pkg/mod/golang.org/x/tools@v0.10.0/go/packages/packages.go:842 +0x4a
golang.org/x/tools/go/packages.(*loader).loadRecursive.func1.1(0x2e656c676f6f6722?)
        /home/user/go/pkg/mod/golang.org/x/tools@v0.10.0/go/packages/packages.go:849 +0x26
created by golang.org/x/tools/go/packages.(*loader).loadRecursive.func1 in goroutine 142
        /home/user/go/pkg/mod/golang.org/x/tools@v0.10.0/go/packages/packages.go:848 +0x94
exit status 2
```
If I modify the path to models to remove the `./` I receive no output to this command.

```Shell
$ go run -mod=mod ariga.io/atlas-provider-gorm load --path models --dialect sqlite
```

My hcl file is as follows:

```data "external_schema" "gorm" {
  program = [
    "go",
    "run",
    "-mod=mod",
    "ariga.io/atlas-provider-gorm",
    "load",
    "--path", "models",
    "--dialect", "sqlite"
  ]
}

env "gorm" {
  src = data.external_schema.gorm.url
  dev = "sqlite://file::memory:?cache=shared"
  migration {
    dir = "file://migrations/sqlite"
  }
  format {
    migrate {
      diff = "{{ sql . \"  \" }}"
    }
  }
}
```
My models package has several files and around 20 tables.

**Comment by giautm** [comment]
hello @joao-intelliway, what is the version of Go you using?

**Comment by joao-intelliway** [comment]
Hello @giautm,

```Shell
$ go version
go version go1.22.0 linux/amd64
```

**Comment by giautm** [comment]
The PR https://github.com/ariga/atlas-provider-gorm/pull/33 should fix this issue

**Comment by giautm** [comment]
Can you please run `go get ariga.io/atlas-provider-gorm@v0.3.1` then try again? Thanks!

**Comment by joao-intelliway** [comment]
Fixed, thanks
